name: Build iOS Tweak
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode & Install ldid
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          brew install ldid || true

      - name: Setup Theos & SDKs
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          rm -rf $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Vendor Dear ImGui
        run: |
          git clone --depth=1 --branch v1.91.5 https://github.com/ocornut/imgui.git imgui

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1 THEOS=$HOME/theos

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-tweak
          path: |
            packages/*.deb
            .theos/obj/*.dylib
            .theos/obj/debug/*.dylib
